name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pedals repo checkout
        uses: actions/checkout@v4
        with:
          repository: SmartyCo/FirmwarePedals
          ref: development
          submodules: recursive
          token: ${{ secrets.PULL_SUBMODULES_TOKEN }}
      - name: Download IDE
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://drive.google.com/uc?id=1PCjyY15nmMv4K6X9C7XFasSYyWFF0yu2&export=download
          filename: stm32cubeide.7z
      - name: Dir list
        run: |
          dir
      - name: Unzip IDE
        run:  |
              7z x stm32cubeide.7z -ostm32cubeide
              dir stm32cubeide
      - name: Pedals repo build
        run: |
          dir ./Sources
          mkdir workspace
          ./stm32cubeide/stm32cubeidec.exe --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./workspace -import ./Sources -build SimPedals/Pedals-F070F6-Bootloader-Production
          ./stm32cubeide/stm32cubeidec.exe --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./workspace -import ./Sources -build SimPedals/Pedals-F070F6-Production
          dir ./Sources
          dir ./workspace
          
          
