name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download IDE
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://drive.google.com/uc?id=10wRFbrSMF6SwYON1aouRotjvOva2qCua&export=download
          target: ${{ runner.temp }}
          filename: stm32cubeide.zip
      - name: Dir list
        run: |
          dir ${{ runner.temp }}
      - name: Unzip IDE
        working-directory: ${{ runner.temp }}
        run:  |
              7z x stm32cubeide.zip -ostm32cubeide
              dir stm32cubeide
